- hosts: semantyca.com
  vars_files:
      - semantyca_secrets.yml
  tasks:
      - name: Stop the service
        ansible.builtin.systemd:
            name: keypracticafe
            state: stopped
        become: yes

      - name: Update the project from GitHub
        ansible.builtin.git:
            clone: yes
            update: yes
            repo: https://github.com/kneoio/kneox.git
            dest: /home/keypractica/fe_server
            force: yes
        become: yes

      - name: Run npm install
        community.general.npm:
            path: /home/keypractica/fe_server
            state: present
        become: yes

      - name: Build the Vue.js application
        ansible.builtin.command:
            cmd: npm run build
            chdir: /home/keypractica/fe_server
        become: yes

      - name: Start the keypracticafe service
        ansible.builtin.systemd:
            name: keypracticafe
            state: started
        become: yes
